####      Dictionary
Key-Value pair mapping container defined withcurly braces {  key : value }

Mutability : Mutable :  Values and Key-Value pair can be modified

Indexing & Slicing :    numeri indexing and sequence slicing are not allowed

Key-Based Indexing :    values are accessed via their key ( e.g .., dict [ "key" ] )

Heterogeneous Data :    Allowed Both key and values can hold multiple data types

Duplicates :            Keys cannot be duplicated (new value overwrite existing keys). Value can be duplicated

In [2]:
student_data = {
                "Name" : ['jhon', 'jay', 'sai', 'bala'],
                "Age"  : [23, 24, 21, 45],
                "Department" : ['CSC', 'EEE', 'IT', 'ECE']
}
print(student_data)
print("1 :",student_data['Name'])      # get values from respective keys
print("2 :",student_data['Age'])
print("3 :",student_data['Department'])

# NOTE : dont put duplicate keys  duplicate values allowed last updates values shows
student_data['Id'] = ['id1','id2','id3','id4']  # Add new key values in dict
student_data['Name'][2] = 'ram' # update exist value using respective key name
#student_data['Name'] = 'ram' # update exist value using respective key name
print("4 :",student_data['Name']) 
print(student_data)

del student_data['Id']  # delete specified key



for key in student_data:    #   accessing dictionary key values using for loop
    print(key,':',student_data[key])

{'Name': ['jhon', 'jay', 'sai', 'bala'], 'Age': [23, 24, 21, 45], 'Department': ['CSC', 'EEE', 'IT', 'ECE']}
1 : ['jhon', 'jay', 'sai', 'bala']
2 : [23, 24, 21, 45]
3 : ['CSC', 'EEE', 'IT', 'ECE']
4 : ['jhon', 'jay', 'ram', 'bala']
{'Name': ['jhon', 'jay', 'ram', 'bala'], 'Age': [23, 24, 21, 45], 'Department': ['CSC', 'EEE', 'IT', 'ECE'], 'Id': ['id1', 'id2', 'id3', 'id4']}
Name : ['jhon', 'jay', 'ram', 'bala']
Age : [23, 24, 21, 45]
Department : ['CSC', 'EEE', 'IT', 'ECE']

####        Accessing dictnary key,values using for loop

In [3]:
stu_data = {
                "Name" : 'jhon',
                "Age"  : 23,
                "Department" : 'CSC'
}

for key in stu_data:
    print(key,":",stu_data[key])      # accesing

for key in stu_data:
    print(stu_data[key]) 


print(len(stu_data))

Name : jhon
Age : 23
Department : CSC
jhon
23
CSC
3

In [4]:
import pandas as pd

Employee_data = {
    'Name' : ['Rajesh','Nasir','Mathiew','Gilbert','Kevin','Navin','Roshan','Kuppusamy','Ajesh','Diya','Mathiew','Jagadheeswari',' Mani','Rashshitha'],
    'Age'  : [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0],
    'Department' : ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'],
    'Salary' : [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0,58000.0],
    'Join_Date' : ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 '],
}



type(Employee_data)
pd.DataFrame(Employee_data)

             Name   Age Department   Salary    Join_Date
0          Rajesh  29.0        Ops  60000.0  21-05-2023
1           Nasir  31.0    IT Tech  62000.0   11-12-2020
2         Mathiew  27.3    Support  58000.0  15-01-2025
3         Gilbert  29.0        Ops  60000.0  21-05-2021
4           Kevin  28.0    Support  61000.0  30-07-2024
5           Navin  35.0    Support  72000.0  19-08-2023
6          Roshan  40.0    IT Tech  64000.0   09-10-2022
7       Kuppusamy  31.0    IT Tech  64000.0   11-12-2020
8           Ajesh  28.0        Ops  60000.0  21-05-2021
9            Diya  28.0    Support  63000.0  30-07-2024
10        Mathiew  31.0    IT Tech  58000.0   11-12-2020
11  Jagadheeswari  30.4    Support  62000.0  15-01-2025
12           Mani  28.0    IT Tech  60000.0   02-12-2023
13     Rashshitha  28.0        Ops  58000.0  21-05-2021

#### dict.items() -> (method) def items() -> dict_items[str, Any]
D.items() -> a set-like object providing a view on D's items

In [5]:
employee_data_list = Employee_data.items()
print(employee_data_list)
print("Type of employee_data_list : ",type(employee_data_list))
print("Employee_data : ",type(Employee_data))

dict_items([('Name', ['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha']), ('Age', [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0]), ('Department', ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops']), ('Salary', [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0]), ('Join_Date', ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 '])])
Type of employee_data_list :  <class 'dict_items'>
Employee_data :  <class 'dict'>

#### dict.copy -> () -> dict[str, Any] -> Return shallow copy of dictionay

D.copy() -> a shallow copy of D

In [ ]:
employee_data_copy = Employee_data.copy()  # return shallow copy of dict
print(employee_data_copy)
print("Type of employee_data_copy : ",type(employee_data_copy))

{'Name': ['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha'], 'Age': [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], 'Department': ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], 'Salary': [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0], 'Join_Date': ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 ']}
Type of employee_data_list_copy :  <class 'dict'>

####    dict.keys( )  -> (method) def keys() -> dict_keys[str, Any]
D.keys() -> a set-like object providing a view on D's keys

In [7]:
employee_data_list_keys = Employee_data.keys()  # return all dict keys
print(employee_data_list_keys)
print("Type of employee_data_list_keys : ",type(employee_data_list_keys))

dict_keys(['Name', 'Age', 'Department', 'Salary', 'Join_Date'])
Type of employee_data_list_keys :  <class 'dict_keys'>

#### dict.values( )  ->  (method) def values() -> dict_values[str, Any]
D.values() -> an object providing a view on D's values

In [8]:
employee_data_list_values = Employee_data.values()  # return all dict values
print(employee_data_list_values)
print("Type of employee_data_list_values : ",type(employee_data_list_values))

dict_values([['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha'], [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0], ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 ']])
Type of employee_data_list_values :  <class 'dict_values'>

#### dict.get() ->  Return the value for key if key is in the dictionary, else default.
(key: str, default: None = None, /) -> (Any | None)

In [9]:
employee_data_get = Employee_data.get('Name')  # return values of specified key
print(employee_data_get)
print("Type of employee_data_get : ",type(employee_data_get))

['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha']
Type of employee_data_get :  <class 'list'>

####    dict.pop() -> remove specified key and return the corresponding value.
(method) def pop(
    key: str,
    /
) -> Any
D.pop(k[,d]) -> v, remove specified key and return the corresponding value.

If the key is not found, return the default if given; otherwise, raise a KeyError.

In [10]:
employee_data_1 = Employee_data.copy() # take copy because original diction affect
print("1 :",employee_data_1)
employee_data_1.pop('Name')  # Note: in-place -> remove specified key and return the corresponding value.
print("2 :",employee_data_1)
print("Type of employee_data_1 : ",type(employee_data_1))

print("3 :",Employee_data)    # original dict not affect

1 : {'Name': ['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha'], 'Age': [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], 'Department': ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], 'Salary': [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0], 'Join_Date': ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 ']}
2 : {'Age': [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], 'Department': ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], 'Salary': [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0], 'Join_Date': ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 ']}
Type of employee_data_1 :  <class 'dict'>
3 : {'Name': ['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha'], 'Age': [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], 'Department': ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], 'Salary': [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0], 'Join_Date': ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 ']}

####    dict.popitem()  -> (method) def popitem() -> tuple[str, Any]

In [11]:
employee_data_1 = Employee_data.copy() # take copy because original diction affect


print("1 :",employee_data_1.popitem())  #  return : remove end (key:value) pairs

print("2 :",employee_data_1)

print("Type of employee_data_1 : ",type(employee_data_1))

print("3 :",Employee_data)    # original dict not affect

pd.DataFrame(employee_data_1)

1 : ('Join_Date', ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 '])
2 : {'Name': ['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha'], 'Age': [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], 'Department': ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], 'Salary': [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0]}
Type of employee_data_1 :  <class 'dict'>
3 : {'Name': ['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha'], 'Age': [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], 'Department': ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], 'Salary': [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0], 'Join_Date': ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 ']}

             Name   Age Department   Salary
0          Rajesh  29.0        Ops  60000.0
1           Nasir  31.0    IT Tech  62000.0
2         Mathiew  27.3    Support  58000.0
3         Gilbert  29.0        Ops  60000.0
4           Kevin  28.0    Support  61000.0
5           Navin  35.0    Support  72000.0
6          Roshan  40.0    IT Tech  64000.0
7       Kuppusamy  31.0    IT Tech  64000.0
8           Ajesh  28.0        Ops  60000.0
9            Diya  28.0    Support  63000.0
10        Mathiew  31.0    IT Tech  58000.0
11  Jagadheeswari  30.4    Support  62000.0
12           Mani  28.0    IT Tech  60000.0
13     Rashshitha  28.0        Ops  58000.0

####    dict.update() -> (method) def update(**kwargs: Any) -> None

In [12]:
print(employee_data_1 )

join_date =  {'Join_Date': ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 ']}

print("1 :",employee_data_1.update(join_date))  #  return : remove end (key:value) pairs

print("2 :",employee_data_1)

print("Type of employee_data_1 : ",type(employee_data_1))

{'Name': ['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha'], 'Age': [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], 'Department': ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], 'Salary': [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0]}
1 : None
2 : {'Name': ['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha'], 'Age': [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], 'Department': ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], 'Salary': [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0], 'Join_Date': ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 ']}
Type of employee_data_1 :  <class 'dict'>

####    dict.setdefault( )  ->  (key: str, default: None = None, /) -> (Any | None)

In [13]:
print(employee_data_1 )

employee_data_1.clear() # empty the dict


print("1 :",employee_data_1)  #  return : remove end (key:value) pairs

{'Name': ['Rajesh', 'Nasir', 'Mathiew', 'Gilbert', 'Kevin', 'Navin', 'Roshan', 'Kuppusamy', 'Ajesh', 'Diya', 'Mathiew', 'Jagadheeswari', ' Mani', 'Rashshitha'], 'Age': [29.0, 31.0, 27.3, 29.0, 28.0, 35.0, 40.0, 31.0, 28.0, 28.0, 31.0, 30.4, 28.0, 28.0], 'Department': ['Ops', 'IT Tech', 'Support', 'Ops', 'Support', 'Support', 'IT Tech', 'IT Tech', 'Ops', 'Support', 'IT Tech', 'Support', 'IT Tech', 'Ops'], 'Salary': [60000.0, 62000.0, 58000.0, 60000.0, 61000.0, 72000.0, 64000.0, 64000.0, 60000.0, 63000.0, 58000.0, 62000.0, 60000.0, 58000.0], 'Join_Date': ['21-05-2023 ', '11-12-2020', '15-01-2025 ', '21-05-2021 ', '30-07-2024 ', '19-08-2023 ', '09-10-2022', '11-12-2020', '21-05-2021 ', '30-07-2024 ', '11-12-2020', '15-01-2025 ', '02-12-2023', '21-05-2021 ']}
1 : {}

#### dict.fromkeys() -> Create a new dictionary with keys from iterable and values set to value.

In [ ]:
employee_data_fromkeys = Employee_data.fromkeys(Employee_data,"OverWrite")  # return all keys fill with specified value
print(employee_data_fromkeys)
print("Type of employee_data_fromkeys : ",type(employee_data_fromkeys))

{'Name': 'OverWrite', 'Age': 'OverWrite', 'Department': 'OverWrite', 'Salary': 'OverWrite', 'Join_Date': 'OverWrite'}
Type of employee_data_fromkeys :  <class 'dict'>